### ISSUE TITLE
ERROR: No working device found.

### ISSUE THREAD

**Issue by heisenberg2980** [homewsn/whsniff#10]
I have followed the instructions to install Whsniff in a raspberry pi, and after connecting the CC2531 with sniffer firmware to one of the usb ports of the raspberry pi I get the error `ERROR: No working device found.` when I execute the command `sudo whsniff -c 11` 

The firmware I flashed into the CC2531 is `zboss_sniffer.hex` and I am assuming this firmware is correct as I am able to sniff on a windows machine using the same CC2531.

**Comment by NateZimmer** [comment]
What is the result of `lsusb` when the dongle is plugged in?

**Comment by heisenberg2980** [comment]
Issue is fixed now, I just read another post regarding sniffer firmware and I realised the firmware used in linux was different, so I flashed the linux firmware (sniffer_fw_cc2531.hex) and the command works now
