### ISSUE TITLE
Issue on kali with CC2531

### ISSUE THREAD

**Issue by kurtjarvis** [homewsn/whsniff#16]
Attempting to use whsniff, it is stuck in the for loop looking for libusb_control_handle to return data. To preface, the hard-coded idProduct had to be changed to 0x16a8 for the CC2531 device. That enables it to find the hardware in the usb list.
However, I put in some debugging statements and the "get identity check" above returns a "-9" which is an error but the code doesn't error-check that result and continues down. Any way I can fix this?

**Comment by schasj** [comment]
I just ran into the exact same issue with building from scratch on Arch Linux. I don't know any more about fixing it than the OP so it sure would be nice id @homewsn would address this.

**Comment by schasj** [comment]
I've dug a little deeper and found that, after setting the idProduct correctly, the for(;;) loop never exits at the comment "// check if powered up". It appears that libusb has to be built from source and NOT stripped for gdb to be of further use.

**Comment by schasj** [comment]
All the above is a red herring. This tool works as described, without modification, IF you flash the CC2531 with the proper code. That code is https://www.ti.com/lit/zip/swrc045 and I followed **only the 3 instructions** here https://xaviercovis.github.io/CC2531-flash-packet-sniffer/#flashingCC2531 in the section "Flashing the CC2531 stick..." and then proceeded with the cc-tool from https://github.com/dashesy/cc-tool.git to flash the extracted HEX file.

I recommend closing this issue.
