### ISSUE TITLE
CC2531 0x16a8

### ISSUE THREAD

**Issue by ottogrunf** [homewsn/whsniff#18]
Hello,

Thank you for this tool!

I purchased a SonOff CC2531, `lsusb` lists it as `0x16a8`, but your code is apparently expecting `0x16ae`. At line 257, there is:

```
if(t_desc.idVendor == 0x0451 && t_desc.idProduct == 0x16ae)
```

I tried my luck by changing it to:

```
if(t_desc.idVendor == 0x0451 && (t_desc.idProduct == 0x16ae || t_desc.idProduct == 0x16a8))
```

This compiles and runs, but I am not catching any packets.

I guess I will have to find a `0x16ae` adapter tu use whsniff. The problem is you only know what you get after the purchase.

Is there anything that could be done to let whsniff support the `0x16a8` adapter?

Thank you!

**Comment by homewsn** [comment]
The USB Vendor ID (VID) and Product ID (PID) are hardcoded into the device's firmware. So you can use any CC2531 USB dongle as long as you can change the dongle firmware to TI SmartRF Packet Sniffer one.
 The firmware can be found on the [TI](https://www.ti.com/tool/PACKET-SNIFFER) or [zigbee2mqtt](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#_1-flashing-the-cc2531-stick) websites. How to flash CC2531 is written, for example, [here](https://www.zigbee2mqtt.io/guide/adapters/flashing/flashing_the_cc2531.html). An inexpensive CC2531 USB dongle that can be flashed, as well as a CC debugger with a cable,  can be bought, for example, on ebay or aliexpress.

**Comment by ottogrunf** [comment]
> 

Ok, thank you. I was led to believe that my dongle already shipped with the right sniffing firmware.
