### ISSUE TITLE
Unable to make on arm64 macOS

### ISSUE THREAD

**Issue by shawnheide** [homewsn/whsniff#19]
I'm still figuring out the switch from Intel macOS to arm64, but I can't figure out how to install this package. Homebrew installs now in /opt/homebrew and I've verified that libusb is installed. Whenever I run `make` it says `ld: library not found for -lusb-1.0`. I've tried changing the `LIBPATH` and `INCLPATH` but neither seem to work. Does anyone else know what I need to get this to work? Thanks for your time and help.

**Comment by pbasista** [comment]
The compiler needs to be made aware of the custom include and library directories. For local usage, it should be sufficient to simply apply e.g. the following patch:

```patch
--- a/Makefile
+++ b/Makefile
@@ -41,11 +41,11 @@ all: $(TARGET)
 
 # target executable
 $(TARGET): $(OBJECTS)
-       $(CC) $(LDFLAGS) -o $(TARGET) $(OBJECTS) $(LIBPATH) $(LIBS)
+       $(CC) $(LDFLAGS) -o $(TARGET) $(OBJECTS) $(LIBPATH) $(LIBS) -L/opt/homebrew/lib
 
 # object files
 $(OBJECTS): $(OBJDIR)/%.o : $(SRCDIR)/%.c $(DEPS) | $(OBJDIR)
-       $(CC) $(CFLAGS) -c $< -o $@ $(INCLPATH)
+       $(CC) $(CFLAGS) -c $< -o $@ $(INCLPATH) -I/opt/homebrew/include
 
 # create object files directory
 $(OBJDIR):
```

**Comment by shawnheide** [comment]
Thanks @pbasista, that worked perfectly! I really appreciate the help.
