### ISSUE TITLE
Add epoch offset

### ISSUE THREAD

**Issue by NateZimmer** [homewsn/whsniff#6]
**Feature Request:** Save host machine's epoch time upon first packet capture and use this as an offset for future timestamps. 

----

I noticed in wireshark my packets were dated in the 1970s. After looking through the code it looks like the packet timestamps are a pure counter upon start of capture. This makes merging data from multiple sources tricky if you don't have absolute timestamps. Granted, I know the timestamp's accuracy would be limited to the host machine but i'd certainly be a nice starting point. Perhaps an optional command line argument?

**Comment by homewsn** [comment]
Thanks for the comment, timestamps really do not depend on the current host time. An additional option is not needed, since the time column preference can be configured in Wireshark itself.

**Comment by NateZimmer** [comment]
Ya beat me to a fix, many thanks! Seemed to work when testing it
