### ISSUE TITLE
Wireshark Error

### ISSUE THREAD

**Issue by jani339** [homewsn/whsniff#8]
Hi, 
I have the following issue. I installed whsniff tool on linux, but every time i try to execute the command "sudo whsniff -c ZIGBEE_CHANNEL_NUMBER | wireshark -k -i -" i get an error in wireshark.

![Issue Zigbee Snifing](https://user-images.githubusercontent.com/70274587/91316757-808e5900-e7b9-11ea-9cda-5ee708368e56.PNG)

OS: ubuntu 19.10
Zigbee Stick/Sniffer --> CC2531 

I hope your able to help me :), Thank you

**Comment by homewsn** [comment]
I have no idea why this happens yet. Could you save whsniff output as pcap file and attach it to the comment?
Why do you use root access?

**Comment by jani339** [comment]
> I have no idea why this happens yet. Could you save whsniff output as pcap file and attach it to the comment?
> Why do you use root access?

Why do you use root access? --> I installed wireshark only useable by the root user. Maybe this could be the issue.
it always gives me errors when i try to write the results into a pcap :(

**Comment by homewsn** [comment]
Try to follow [this advice](https://askubuntu.com/a/74064) to allow Wireshark to sniff without root access.
You can also read [the official page](https://wiki.wireshark.org/CaptureSetup/CapturePrivileges).

**Comment by jani339** [comment]
> Try to follow [this advice](https://askubuntu.com/a/74064) to allow Wireshark to sniff without root access.
> You can also read [the official page](https://wiki.wireshark.org/CaptureSetup/CapturePrivileges).

Still the same Issue :(

**Comment by NateZimmer** [comment]
Hmmm, this works great for me on multiple linux distros. Your issue is specific to your setup. 
1. Have you validated the dongle works in windows?
1. Have you validated the dongle is enumerated properly in linux?
1. Still waiting for your .pcap file export of the program `sudo whsniff -c channel >myLog.pcap` , might help diagnose

**Comment by JeanProfite** [comment]
Hello, same issue here.

![image](https://user-images.githubusercontent.com/18187110/151072738-0f004c88-907e-4d65-96af-9886c07366c2.png)

![image](https://user-images.githubusercontent.com/18187110/151072665-926689fd-50a6-49fc-a604-e53c6446d670.png)

I have a Sonoff Zigbee 3.0 USB Dongle Plus on Ubuntu.
Properly mounted i think:
![image](https://user-images.githubusercontent.com/18187110/151072354-ff5bf822-c45d-424d-b17e-bc295be51969.png)

And here is my .pcap [myLog.zip](https://github.com/homewsn/whsniff/files/7937720/myLog.zip) file when y launch `sudo whsniff -c 11 >myLog.pcap`.

I have followed [this](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#_3-sniffing-traffic).

**Comment by homewsn** [comment]
Your myLog.pcap file contains one string: "ERROR: No working device found.". 
[This means](https://github.com/homewsn/whsniff/blob/master/src/whsniff.c#L303) that the CC2531 USB dongle with [the appropriate firmware](https://www.zigbee2mqtt.io/advanced/zigbee/04_sniff_zigbee_traffic.html#linux) (idVendor=0x0451, idProduct=0x16ae) is not connected to the computer.
As far as I understand, [Sonoff Zigbee 3.0 USB Dongle Plus](https://sonoff.tech/product/diy-smart-switch/sonoff-dongle-plus/) is made on the basis of CC2652P. So you need another sniffer software, not whsniff.

**Comment by JeanProfite** [comment]
My bad, obviously your are right.
Thank you !
